version: '3.8'
services:
  app:
    build: ./
    environment:
      - NODE_ENV=e2e-test
    links:
      - mariadb
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: cities
      MYSQL_USER: jaoafa
      MYSQL_PASSWORD: jaoafa
      TZ: Asia/Tokyo
